### ISSUE TITLE
Problem with Win32Window#focus

### ISSUE THREAD

**Issue by rz7d** [underecho/MTwit#17]
focus() メソッドを呼び出す際に、詳細不明なエラーが発生します。

## 原因と事実
No error message is available となるのは win32gui が悪そう

```
Traceback (most recent call last):
  File "C:\Users\azure\Documents\workspace\MTwit\mTwit\ui\MainWindow.py", line 143, in iconActivated
    self.ShowOrHide()
  File "C:\Users\azure\Documents\workspace\MTwit\mTwit\ui\MainWindow.py", line 147, in ShowOrHide
    self.showEvent_()
  File "C:\Users\azure\Documents\workspace\MTwit\mTwit\ui\MainWindow.py", line 180, in showEvent_
    self.w.focus()
  File "C:\Users\azure\Documents\workspace\MTwit\mTwit\ui\ui_base.py", line 30, in focus
    win32gui.SetForegroundWindow(self.handle)
pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')
```

**Comment by underecho** [comment]
再現できません、発生するタイミング（ショートカットを用いた表示切り替え時...など）もしくは発生するまでの手順を明記してください。

**Comment by rz7d** [comment]
私も再現できていませんので、スタックトレースから追って再現でき次第解決します。

**Comment by rz7d** [comment]
SetForegroundWindowの仕様の可能性があるが、errnoが0なので謎

**Comment by underecho** [comment]
俺もこれ出たけど1度出てから全然出ないし例え出たとしても動作に支障がないんだよな

**Comment by underecho** [comment]
動作が止まるわけでもなくログのごみになるだけなのでissueとしてもいらないかなと

**Comment by underecho** [comment]
普通に異常終了したので
